version: 2
workflows: # Define a Workflow running the build job, then the deploy job
   version: 2
   build-deploy: # Make a workflow to build and deploy your project
     jobs:
       - build
       - deploy:
           requires:
             - build # Only run deploy job once the build job has completed
           filters:
             branches:
               only: main # Only deploy when the commit is on the Master branch
jobs:
  build:
    filters:
      branches:
        only:
          - main

    docker:
      - image: circleci/node:15
    working_directory: ~/angularFirebase

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}

            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm install --save-dev firebase-tools
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Angular Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
  deploy:
    filters:
      branches:
        only:
          - main

    docker:
      - image: circleci/node:15
    working_directory: ~/angularFirebase

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum "package-lock.json" }}

            - v1-npm-deps-
      - run:
          name: Install Dependencies
          command: npm install
      - run: npm install --save-dev firebase-tools
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Angular Build
          command: npm run build
      - run:
          name: Firebase Deploy
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
