# version: 2
# "on":
#   push:
#     branches:
#       - main
# jobs:
#   build:
#     filters:
#       branches:
#         only:
#          - develop

#     docker:
#       - image: circleci/node:15
#     working_directory: ~/angularFirebase

#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - v1-npm-deps-{{ checksum "package-lock.json" }}

#             - v1-npm-deps-
#       - run:
#           name: Install Dependencies
#           command: npm install
#       - run: npm install --save-dev firebase-tools
#       - save_cache:
#           key: v1-npm-deps-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: Angular Build
#           command: npm run build
#       - run:
#           name: Firebase Deploy
#           command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"

version: 2
jobs:
  build:
    filters:
      branches:
        only:
          - develop
    docker:
      - image: circleci/node:4.8.2 # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
